### ISSUE TITLE
Feature request for some pretty useful codes

### ISSUE THREAD

**Issue by wolfmanjm** [ambrop72/aprinter#2]
M220 Snnn where nnn is the percentage speed is very useful for fine tuning prints.
M92 Ennn which sets e steps/mm, this is essential for those of us that tweak extruder flow for the different filaments by changing E steps.
M204 Snnn which sets acceleration would be nice
M80/81 for turning Power supply on and off (for atx an open collector output is best)
M500 and associated for storing these in eeprom.

Allow limiting of speed in Cartesian axis... eg I need to limit speed in Z only to half the speed in X or Y.

**Comment by ambrop72** [comment]
Hey,
Most of this is done, though some of it is via the runtime-configuration system rather than the specific commands you mentioned.

- M220: Implemented.
- M92 Ennn: Use M926 IEStepsPerUnit Vnnn && M930.
- M204 Snnn: Use M926 I<axis>MaxAccel Vnnn && M930.
- M500, M501, M502, M503 are implemented as part of the runtime-configuration system. Note M930 is needed to apply any settings. Depending on the board configuration this saves either to EEPROM or a file on SD card.
- Allow limiting of speed in Cartesian axis: Implemented.

Power supply stuff is not done yet though. Closing this anyway.
